// Generated by extrovert/skills/tools/generate-agent-release.mjs; do not edit.
export const AGENT_RELEASE = {
  "schema_version": 1,
  "release_version": "0.1.0-pre.40",
  "channel": "next",
  "skills": {
    "agent-email-architecture": {
      "version": "0.1.0-pre.40",
      "sha256": "912ef1222efbbc14b4866afafa333bac41fb361d28ec91544a2b3e2d567d6ab1",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/agent-email-architecture"
    },
    "extrovert-sdk": {
      "version": "0.1.0-pre.40",
      "sha256": "de6e7928b9f844b331c545fab446e0480fab5f03a1c4bd26044d84af1081a0df",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-sdk"
    },
    "extrovert-connect": {
      "version": "0.1.0-pre.40",
      "sha256": "2b60a1d05467acc9649a5de5a6eb1e6c3e8e156971a2cfd32bd99ac9b25a8707",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-connect"
    },
    "extrovert-admin": {
      "version": "0.1.0-pre.40",
      "sha256": "78efc4b4063857023021434ceb1b6c6192c75fba3c411ab779cee126b65383bb",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-admin"
    },
    "extrovert-manage-inboxes": {
      "version": "0.1.0-pre.40",
      "sha256": "f5a05d1ca2bb152716160d575b2b270952fbf4e8ed8c6f3e12051b2fac8a4a4d",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-manage-inboxes"
    },
    "extrovert-read-inbox": {
      "version": "0.1.0-pre.40",
      "sha256": "760a5b193a70320b713361ba54dce17b601c49169549e5c42a6d8c862d6d928c",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-read-inbox"
    },
    "extrovert-send-email": {
      "version": "0.1.0-pre.40",
      "sha256": "70690a2dc28f37d5bc8c1e34c6a94a5091c5cdd92ae0f4911b9a894438193196",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-send-email"
    },
    "extrovert-writing-rules": {
      "version": "0.1.0-pre.40",
      "sha256": "38f807c5f2b0b6ae05a68a05a3da4c71f22c25a9e16a58ccf106fc5531982037",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-writing-rules"
    },
    "wait-for-otp": {
      "version": "0.1.0-pre.40",
      "sha256": "ccb2a8781e4b89d9397075e825fe61cdae8fc032e5e6f92e619de34714e50870",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/wait-for-otp"
    },
    "configure-himalaya": {
      "version": "0.1.0-pre.40",
      "sha256": "099a86289a79cb3d30ccd3200927ccc6869651ab2cbb74868161f64275dc9e32",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/configure-himalaya"
    }
  }
} as const;
