// Generated by extrovert/skills/tools/generate-agent-release.mjs; do not edit.
export const AGENT_RELEASE = {
  "schema_version": 1,
  "release_version": "0.1.0-pre.22",
  "channel": "next",
  "skills": {
    "agent-email-architecture": {
      "version": "0.1.0-pre.22",
      "sha256": "49103b83c0cfb0e600a205a336f5c7f0aa407974b3d85610ebe47d6819c84582",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/agent-email-architecture"
    },
    "extrovert-sdk": {
      "version": "0.1.0-pre.22",
      "sha256": "be27f9864920a13c748859466134a66858638a696fdde1c87b4a7c79175ec493",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-sdk"
    },
    "extrovert-connect": {
      "version": "0.1.0-pre.22",
      "sha256": "bf3b961500e54ad054edfd3ea531679fd0e4d12d213e434ad6ffbcbf034509fb",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-connect"
    },
    "extrovert-manage-inboxes": {
      "version": "0.1.0-pre.22",
      "sha256": "6026bc0f63f286a30743ffc1ce3c6e00d82d61f8a27a28778da5d318d968f97e",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-manage-inboxes"
    },
    "extrovert-read-inbox": {
      "version": "0.1.0-pre.22",
      "sha256": "990b40764b820fa6f57ba47e4bef0f86fed1b111d5e814b6c1b4e3c1e175d971",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-read-inbox"
    },
    "extrovert-send-email": {
      "version": "0.1.0-pre.22",
      "sha256": "10d50b1d4796313ce83739ea8ac45950b1ef682f1827f310ec86b8645e60046f",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-send-email"
    },
    "extrovert-writing-rules": {
      "version": "0.1.0-pre.22",
      "sha256": "da571a6d83b08df72535daf9c66d28bc660ac2cfc01981ce9c487de437e2e2ac",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-writing-rules"
    },
    "wait-for-otp": {
      "version": "0.1.0-pre.22",
      "sha256": "798a62de0a9fec670c383ad8addbaadae24b2d50e2bc2b9e1370693f089fa520",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/wait-for-otp"
    },
    "configure-himalaya": {
      "version": "0.1.0-pre.22",
      "sha256": "60848339970b16fb62a4a738df8725f86d61c8643d28dc7c661349f7dcc24020",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/configure-himalaya"
    }
  }
} as const;
