// Generated by extrovert/skills/tools/generate-agent-release.mjs; do not edit.
export const AGENT_RELEASE = {
  "schema_version": 1,
  "release_version": "0.1.0-pre.36",
  "channel": "next",
  "skills": {
    "agent-email-architecture": {
      "version": "0.1.0-pre.36",
      "sha256": "a1386bd2d5bf1b743b02181b35cbe1787aba93ec306a1f21ef40731cb5311173",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/agent-email-architecture"
    },
    "extrovert-sdk": {
      "version": "0.1.0-pre.36",
      "sha256": "ef2c2424843fa1373abb6868d38a69831bdf15d2e57cc4443196873d168ff466",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-sdk"
    },
    "extrovert-connect": {
      "version": "0.1.0-pre.36",
      "sha256": "28f0d4ea4b459ecdab7a22240e8b41b4f11d29847090478e7e96e1afbc58408a",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-connect"
    },
    "extrovert-manage-inboxes": {
      "version": "0.1.0-pre.36",
      "sha256": "98f4b48b37eae1d43f33e91a673addd8e0ac624632bf3885013681e48a0a219e",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-manage-inboxes"
    },
    "extrovert-read-inbox": {
      "version": "0.1.0-pre.36",
      "sha256": "c88b80423933f7d68c3108e79a40e77248e12e7ad2a8b71fe84bea7be850a904",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-read-inbox"
    },
    "extrovert-send-email": {
      "version": "0.1.0-pre.36",
      "sha256": "19cc08fbf9fe846b7acb0ac7230a08074028fd2ec4020909a7db0132814e0efa",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-send-email"
    },
    "extrovert-writing-rules": {
      "version": "0.1.0-pre.36",
      "sha256": "2f3846a3c4fff9d86ecbfc21eabbab60ac09ddafb6d15e6d237a25ca6d7952a6",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/extrovert-writing-rules"
    },
    "wait-for-otp": {
      "version": "0.1.0-pre.36",
      "sha256": "86d3dbd8c76976923ce8b3660219151cfdec67e1c9b5bf63befe02b437bcd117",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/wait-for-otp"
    },
    "configure-himalaya": {
      "version": "0.1.0-pre.36",
      "sha256": "7f8d2048bc045fa2813de7cb7deb1c0a8b55868cd6a288974f57041074e227b1",
      "source": "https://github.com/extrovert-dot-dev/extrovert-skills/tree/main/configure-himalaya"
    }
  }
} as const;
