// Generated by extrovert/release/generate-assistant-release.mjs; do not edit.
export const ASSISTANT_RELEASE = {
  "schema_version": 1,
  "release_version": "0.1.3",
  "profile": "assistant",
  "resource_path": "/assistant/mcp",
  "skills": {
    "extrovert-connect": {
      "version": "0.1.3",
      "sha256": "4ab7ec7a6f00164c6be2ecbe5e544d93c16248cfdd7e0bb70038e3b3126837c4"
    },
    "extrovert-read-inbox": {
      "version": "0.1.3",
      "sha256": "45992f1c932dbe1be8744ba61531a957f44047eab52319b47730abd419b34424"
    },
    "extrovert-send-email": {
      "version": "0.1.3",
      "sha256": "d638ce11ffa166decb7c061c4510ba5ef5b9d38b325cf03b0e90acdee6f4d31d"
    },
    "extrovert-writing-rules": {
      "version": "0.1.3",
      "sha256": "9ad6bd5f36d2d4ed25bb97a6bdd6a2dacd30145d39906f9f2d2a1477cc4f5e5d"
    },
    "wait-for-otp": {
      "version": "0.1.3",
      "sha256": "e947d67ed4df33489603b80521ce0ccdca376b1d9e62b788c232b708af356219"
    },
    "extrovert-support": {
      "version": "0.1.3",
      "sha256": "da19cf2af9ef920370f666408d295a7504dc2294f4ebf2928205db788ef5ca1c"
    }
  }
} as const;
