// Generated by extrovert/release/generate-assistant-release.mjs; do not edit.
export const ASSISTANT_RELEASE = {
  "schema_version": 1,
  "release_version": "0.1.2",
  "profile": "assistant",
  "resource_path": "/assistant/mcp",
  "skills": {
    "extrovert-connect": {
      "version": "0.1.2",
      "sha256": "a67b8b34be6f953881ecaa8354cea469800b01fcf739d821174890fafbbc5129"
    },
    "extrovert-manage-inboxes": {
      "version": "0.1.2",
      "sha256": "e9506eb45be9dbfda5e43e21fd40b3990c94fc399acee90a648f33546eaacd3d"
    },
    "extrovert-read-inbox": {
      "version": "0.1.2",
      "sha256": "2f4519790f0b6cc4060833db3266d87ca845c18975668b4efa5f93fd1a27e130"
    },
    "extrovert-send-email": {
      "version": "0.1.2",
      "sha256": "c9b4709b61394e21ceaddae58676b2095c6fd07048cdcfb82b8893f6946a00e6"
    },
    "extrovert-writing-rules": {
      "version": "0.1.2",
      "sha256": "3799e78c231655d0ae4aa84483a8c18c26588c5dc36c3e831ae4b1a5a0c1635e"
    },
    "wait-for-otp": {
      "version": "0.1.2",
      "sha256": "a486377bbfdcd4436e7bc8d1fe23154f863f2cfc014b400ad32fc07d9be701bd"
    },
    "extrovert-support": {
      "version": "0.1.2",
      "sha256": "bc0a1a222f4e763165da61305805f03804107175f6306b6f20d5f1df6a958790"
    }
  }
} as const;
