// Generated by extrovert/release/generate-assistant-release.mjs; do not edit.
export const ASSISTANT_RELEASE = {
  "schema_version": 1,
  "release_version": "0.1.0",
  "profile": "assistant",
  "resource_path": "/assistant/mcp",
  "skills": {
    "extrovert-connect": {
      "version": "0.1.0",
      "sha256": "23d63d0f74217f6004b82c4d254bf2d0ef10fd2122c7d545519f61b7627b5404"
    },
    "extrovert-manage-inboxes": {
      "version": "0.1.0",
      "sha256": "934447b6034a9c6e807e574781ed0183d8ab8796241965265a321dff4c2ded91"
    },
    "extrovert-read-inbox": {
      "version": "0.1.0",
      "sha256": "dc6c007b10cbe960fde3163d25883c0298ca94d02d828553c7cd8746a18559d0"
    },
    "extrovert-send-email": {
      "version": "0.1.0",
      "sha256": "bb6dd74e64099640fb21bc65171c5db351afbb364d6df93b89ef07b7cba165b7"
    },
    "extrovert-writing-rules": {
      "version": "0.1.0",
      "sha256": "4980d79389adaae5ad7fc421db61f30185e45444d9b10d441043088e7260a129"
    },
    "wait-for-otp": {
      "version": "0.1.0",
      "sha256": "0b83a4567babe8cb06944de292516e6f0b0276c3abd9779dc26856a4bba58468"
    },
    "extrovert-support": {
      "version": "0.1.0",
      "sha256": "eef119ca614dd15383ccf9dd35866a22d913048214b7e4eb46204087236641ef"
    }
  }
} as const;
